USE sakila;

-- 1. List the number of films per category
SELECT 
    category.name AS category,
    COUNT(film_category.film_id) AS number_of_films
FROM category
JOIN film_category
    ON category.category_id = film_category.category_id
GROUP BY category.category_id, category.name;

-- 2. Retrieve the store ID, city, and country for each store
SELECT 
    store.store_id,
    city.city,
    country.country
FROM store
JOIN address
    ON store.address_id = address.address_id
JOIN city
    ON address.city_id = city.city_id
JOIN country
    ON city.country_id = country.country_id;

-- 3. Calculate the total revenue generated by each store in dollars
SELECT 
    store.store_id,
    SUM(payment.amount) AS total_revenue
FROM store
JOIN staff
    ON store.store_id = staff.store_id
JOIN payment
    ON staff.staff_id = payment.staff_id
GROUP BY store.store_id;

-- 4. Determine the average running time of films for each category
SELECT 
    category.name AS category,
    ROUND(AVG(film.length), 2) AS average_running_time
FROM category
JOIN film_category
    ON category.category_id = film_category.category_id
JOIN film
    ON film_category.film_id = film.film_id
GROUP BY category.category_id, category.name;